#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "myspeed"
name = "MySpeed"
description.en = "Speed test analysis software"
description.fr = "Logiciel d'analyse de test de vitesse"

version = "1.0.9~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://myspeed.dev/"
admindoc = "https://docs.myspeed.dev/"
code = "https://github.com/gnmyt/myspeed"
fund = "https://ko-fi.com/gnmyt"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    url = "https://github.com/gnmyt/myspeed/releases/download/v1.0.9/MySpeed-1.0.9.zip"
    sha256 = "7cc615c146c00d4e3f35109e7c0cc153255248a3d26254195897e7514bccc182"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5216
